In [2]:
import numpy as np

In [4]:
a = np.arange(1, 7, 1).reshape([2,3])

In [5]:
print(a)

[[1 2 3]
 [4 5 6]]


In [11]:
a.ndim


2

In [12]:
a.shape

(2, 3)

In [13]:
a.size

6

In [14]:
a.dtype

dtype('int32')

In [15]:
a.itemsize

4

In [16]:
np.linspace(1,2,num=5,retstep="True")

(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)

In [20]:
b=a.reshape(3,2)
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [28]:
c=np.arange(1,9).reshape(2,2,2)
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [35]:
np.array([(1,2),(3,4)])

array([[1, 2],
       [3, 4]])

In [41]:
r=a
r

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
f=a.flatten() #Flatten passes copy of original array to f
f

array([1, 2, 3, 4, 5, 6])

In [38]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
rav=r.ravel() # Ravel passes a view of original array to rav
rav

array([1, 2, 3, 4, 5, 6])

In [43]:
r

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
rav[0]=77
rav

array([77,  2,  3,  4,  5,  6])

In [48]:
r

array([[77,  2,  3],
       [ 4,  5,  6]])

In [49]:
f[0]=55
f

array([55,  2,  3,  4,  5,  6])

In [50]:
a #change in flattened array does not reflect back in original array a, but change in ravel array reflects in r and a

array([[77,  2,  3],
       [ 4,  5,  6]])

In [53]:
np.ones(5,dtype=np.int16 )

array([1, 1, 1, 1, 1], dtype=int16)

In [65]:
z=np.zeros((2,2))
z

array([[0., 0.],
       [0., 0.]])

In [57]:
np.empty((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [62]:
np.full((3,2),12)

array([[12, 12],
       [12, 12],
       [12, 12]])

In [66]:
i=np.eye(2)
i

array([[1., 0.],
       [0., 1.]])

In [69]:
cat0=np.concatenate((z,i),axis=0)         #concatenate
cat0

array([[0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 1.]])

In [70]:
cat1=np.concatenate((z,i),axis=1)
cat1

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [73]:
catN=np.concatenate((z,i),axis=None)
catN

array([0., 0., 0., 0., 1., 0., 0., 1.])

In [76]:
random_array=np.random.rand(2,2)        #random values are filled
random_array

array([[0.50579456, 0.6670526 ],
       [0.05070745, 0.53250985]])

In [92]:
 #slicing of 1D array
 o=np.array([1,2,3,4,5,6,7,8])
o
    

array([1, 2, 3, 4, 5, 6, 7, 8])

In [97]:
o[7]

8

In [94]:
# equivalent to a[0:6:2] = 1000;
# from start to position 6, exclusive, set every 2nd element to 1000
o[:6:2] = 1000
o

array([1000,    2, 1000,    4, 1000,    6,    7,    8])

In [98]:
o[2:6]

array([1000,    4, 1000,    6])

In [100]:
o[-1] #lasst element

8

In [101]:
o[ : :-1] #reversed array

array([   8,    7,    6, 1000,    4, 1000,    2, 1000])

In [105]:
for oo in o:
    print(oo**(1/10))

1.9952623149688797
1.0717734625362931
1.9952623149688797
1.148698354997035
1.9952623149688797
1.1962311988513155
1.214814044039067
1.2311444133449163


In [106]:
#slicing 2D array
a[1,2]

6

In [111]:
a

array([[77,  2,  3],
       [ 4,  5,  6]])

In [112]:
a[0:2, 1]   # each row in the second column of a

array([2, 5])

In [110]:
a[:, 1]     

array([2, 5])

In [99]:
a[ : :-1]

array([[ 4,  5,  6],
       [77,  2,  3]])

In [116]:
a[1:2,:]

array([[4, 5, 6]])

In [117]:
a[-1]# the last row. Equivalent to a[-1,:]

array([4, 5, 6])

In [79]:
a

array([[77,  2,  3],
       [ 4,  5,  6]])

In [88]:
a.argmax()  ## find the index of maximum value. 

0

In [90]:
cat0.argmax()

4

In [80]:
indmax0 = a.argmax(axis=0)    # index of the maxima for each series
indmax0

array([0, 1, 1], dtype=int64)

In [81]:
indmax1 = a.argmax(axis=1)    # index of the maxima for each series
indmax1

array([0, 2], dtype=int64)

In [118]:
a.argmin()

1

In [119]:
cat0.argmin()

0

In [120]:
indmin0= a.argmin(axis=0)
indmin0

array([1, 0, 0], dtype=int64)

In [121]:
indmin1= a.argmin(axis=1)
indmin1

array([1, 0], dtype=int64)

In [122]:
a.max()

77

In [123]:
a.min()

2

In [124]:
a.mean()

16.166666666666668

In [125]:
a.std()  #standard deviation

27.236107569833756

In [127]:
z.dot(i)

array([[0., 0.],
       [0., 0.]])

In [133]:
g=np.array([(2,2),(2,2)]) 
g.dot(g)

array([[8, 8],
       [8, 8]])

In [135]:
np.square(g)

array([[4, 4],
       [4, 4]], dtype=int32)

In [136]:
np.sqrt(g)

array([[1.41421356, 1.41421356],
       [1.41421356, 1.41421356]])

In [137]:
np.abs(g)

array([[2, 2],
       [2, 2]])

In [139]:
q=[1,-1]
np.abs(q)                                 #absolute value

array([1, 1])

In [3]:
np.absolute(2+3j)            #absolute value

3.605551275463989

In [140]:
np.exp(g)

array([[7.3890561, 7.3890561],
       [7.3890561, 7.3890561]])

In [145]:
p=[1,-4,33,-48,-9]
np.sign(p)          #check sign of array elements

array([ 1, -1,  1, -1, -1])

In [142]:
np.sign(7-3j)  #check sign of real nos

(1+0j)

In [143]:
np.sign(-7+2j)

(-1+0j)

In [146]:
l=[1,2,3,4]
m=[5,5,5,5]
np.mod(m,l)   # m%l

array([0, 1, 2, 1], dtype=int32)